spring:
#  profiles:
#    active: ${ACTIVE_PROFILE:dev}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/ShopOnline?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Abc123456789@}

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # jdbc:
        #   time_zone: UTC
        #globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
#    host: ${EMAIL_HOST}
#    port: ${EMAIL_PORT}
#    username: ${EMAIL_ID}
#    password: ${EMAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    username: nuyenhongdang@gmail.com
    password: pcba kosk gxht cued
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
#      host: ${VERIFY_EMAIL_HOST}
      host: http://localhost:8080
  servlet:
    multipart:
      max-file-size: ${FILE_CAPACITY:50MB}
      max-request-size: ${FILE_CAPACITY:50MB}

server:
  port: ${SERVER_PORT:8088}
api:
  prefix: api/${VERSION_API:v1}
